# Generated by Django 2.0.3 on 2018-03-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortner',
            name='hash',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
