# Generated by Django 2.0.3 on 2018-03-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner_app', '0003_auto_20180318_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortner',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
    ]
